/**
 * Supabase Database TypeScript Definitions
 * 
 * Note: This file provides a strong typing foundation for the Anchor Fashion Enterprise Ecommerce platform.
 * In production, this file is typically auto-generated by the Supabase CLI using:
 * `npx supabase gen types typescript --local > supabase/types/database.types.ts`
 * 
 * Please run the above command after applying all migrations to the local or remote database
 * to ensure exact synchronization with the PostgreSQL schema.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      roles: {
        Row: {
          id: string
          name: string
          description: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          description?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          description?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      profiles: {
        Row: {
          id: string
          first_name: string | null
          last_name: string | null
          phone: string | null
          role_id: string | null
          avatar_url: string | null
          is_active: boolean | null
          deleted_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          first_name?: string | null
          last_name?: string | null
          phone?: string | null
          role_id?: string | null
          avatar_url?: string | null
          is_active?: boolean | null
          deleted_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          first_name?: string | null
          last_name?: string | null
          phone?: string | null
          role_id?: string | null
          avatar_url?: string | null
          is_active?: boolean | null
          deleted_at?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      // [Auto-generated definitions for all 100+ tables will populate here]
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
