export const AUTH_ROLES = {
  SUPERADMIN: 'SUPERADMIN',
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  WAREHOUSE_MANAGER: 'WAREHOUSE_MANAGER',
  MARKETING_MANAGER: 'MARKETING_MANAGER',
  FINANCE_MANAGER: 'FINANCE_MANAGER',
  CUSTOMER: 'CUSTOMER',
} as const;

export type AuthRole = typeof AUTH_ROLES[keyof typeof AUTH_ROLES];

export const ADMIN_ROLES = [AUTH_ROLES.SUPERADMIN, AUTH_ROLES.ADMIN];

export const MANAGER_ROLES = [
  AUTH_ROLES.SUPERADMIN,
  AUTH_ROLES.ADMIN,
  AUTH_ROLES.MANAGER,
  AUTH_ROLES.WAREHOUSE_MANAGER,
  AUTH_ROLES.MARKETING_MANAGER,
  AUTH_ROLES.FINANCE_MANAGER,
];
